/* BLANK */
R"(
|    |
|    |
|    |
|    |
)"_mt_2_2,
/* MOVE */
R"(
|  o |
| ooo|
|o o |
|  o |
)"_mt_2_2,
/* TURN_LEFT */
R"(
|    |
|o o |
|oo  |
|ooo |
)"_mt_2_2,
/* TURN_RIGHT */
R"(
|    |
| o o|
|  oo|
| ooo|
)"_mt_2_2,
/* WAIT */
R"(
|    |
| oo |
| oo |
|    |
)"_mt_2_2,
/* PICKUP */
R"(
|   o|
|  o |
|o o |
| o  |
)"_mt_2_2,
/* SUB */
R"(
|  o |
| o  |
|  o |
| oo |
)"_mt_2_2,
/* ONE */
R"(
|  o |
| oo |
|  o |
|  o |
)"_mt_2_2,
/* TWO */
R"(
| oo |
|   o|
|  o |
| ooo|
)"_mt_2_2,
/* WALL */
R"(
|oooo|
|o  o|
|o  o|
|oooo|
)"_mt_2_2,
/* ITEM */
R"(
|    |
| oo |
| oo |
|    |
)"_mt_2_2,
/* BORDER_TOP */
R"(
|    |
|    |
|    |
|oooo|
)"_mt_2_2,
/* BORDER_BOT */
R"(
|oooo|
|    |
|    |
|    |
)"_mt_2_2,
/* BORDER_LEFT */
R"(
|   o|
|   o|
|   o|
|   o|
)"_mt_2_2,
/* BORDER_RIGHT */
R"(
|o   |
|o   |
|o   |
|o   |
)"_mt_2_2,
/* BORDER_TL_CORNER */
R"(
|    |
|    |
|    |
|   o|
)"_mt_2_2,
/* BORDER_TR_CORNER */
R"(
|    |
|    |
|    |
|o   |
)"_mt_2_2,
/* BORDER_BL_CORNER */
R"(
|   o|
|    |
|    |
|    |
)"_mt_2_2,
/* BORDER_BR_CORNER */
R"(
|o   |
|    |
|    |
|    |
)"_mt_2_2,
/* SEPARATOR */
R"(
|    |
|oooo|
|oooo|
|    |
)"_mt_2_2,

